server:
  port: 8082

spring:
  application:
    name: andrea360_backend

  datasource:
    url: jdbc:postgresql://localhost:5433/andrea360
    username: andrea360
    password: andrea360
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # TEMP for now; later we switch to Flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: warn

stripe:
  secretKey: ${STRIPE_SECRET_KEY:}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}
  successUrl: http://localhost:5173/payments/success?session_id={CHECKOUT_SESSION_ID}
  cancelUrl: http://localhost:5173/payments/cancel

